module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [2, "always", ["add", "update", "fix", "refactor", "delete"]],
    "scope-enum": [
      2,
      "always",
      [
        "ai",
        "be(nodejs)",
        "be(nestjs)",
        "be(supabase)",
        "clean-code",
        "cs(network)",
        "fe(a11y)",
        "fe(css)",
        "fe(dp)",
        "fe(env)",
        "fe(html)",
        "fe(i18n)",
        "fe(interactive-web)",
        "fe(js)",
        "fe(next)",
        "fe(opt)",
        "fe(react)",
        "fe(rn)",
        "fe(test)",
        "fe(ts)",
        "infra(aws)",
        "infra(cicd)",
        "infra(docker)",
        "infra(git)",
        "infra(linux)",
        "seo",
      ],
    ],
    "scope-empty": [2, "never"],
  },
};
